server:
  port: 8085

spring:
  application:
    name: microservice-base-service

eureka:
  client:
    # 是否需要注册到注册中心
    register-with-eureka: true
    # 是否需要从注册中心获取服务列表
    fetch-registry: true
    serviceUrl:
      # 声明服务注册中心地址
      defaultZone: http://192.168.21.1:8080/eureka/
